/*
  os recursos (componentes, diretivas etc) são importados aqui
  individualmente e de forma consolidada para minimizar o
  tamanho do bundle final.
  https://bootstrap-vue.org/docs#individual-components-and-directives
*/

export {
  BContainer,
  BRow as Row,
  BCol as Col,
  BFormGroup,
  BFormCheckbox,
  BFormRadioGroup,
  BFormRadio,
  BAlert,
  BCollapse,
  BFormRow,
  BButton,
  BFormInvalidFeedback,
  BFormInput,
  BFormTextarea,
  BFormSelect,
  BFormTags,
  BFormTag,
  BModal,
  BOverlay,
  BSpinner,
  BTable,
  BPagination,
  BNavbar,
  BNavbarBrand,
  BNavbarNav,
  BNavText,
  BNavItemDropdown,
  BNavItem,
  BBreadcrumb,
  BAvatar,
  BDropdownItem,
  BSidebar,
  BInputGroup,
  BInputGroupAppend,
  BInputGroupText,
  BImg,
  BIconCaretDownFill,
  BIconCaretUpFill,
  BIconCircleFill,
  BIconCheckCircleFill,
  BIconChevronUp,
  BIconChevronDown,
  BIconChevronRight,
  BIconDownload,
  BIconExclamationTriangleFill,
  BIconEyeFill,
  BIconFileEarmarkTextFill,
  BIconFiles,
  BIconInfoCircleFill,
  BIconList,
  BIconPencilFill,
  BIconPencilSquare,
  BIconPeopleFill,
  BIconReplyFill,
  BIconSearch,
  BIconTrashFill,
  BIconX,
  BIconXCircleFill,
  VBToggle,
  VBTooltip,
  BVToastPlugin
} from 'bootstrap-vue';
